// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CartController from "./cart_controller"
application.register("cart", CartController)

import ColorSelectorController from "./color_selector_controller"
application.register("color-selector", ColorSelectorController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
